- name: Runner_Ladder_2x_5x
  type: RUNNER
  params:
    take_profit_levels:
      - { xn: 2.0, fraction: 0.6 }
      - { xn: 5.0, fraction: 0.4 }
    time_stop_minutes: 20160
    use_high_for_targets: true
    exit_on_first_tp: false
    allow_partial_fills: true



- name: Runner_Ladder_3x_7x
  type: RUNNER
  params:
    take_profit_levels:
      - { xn: 3.0, fraction: 0.5 }
      - { xn: 7.0, fraction: 0.5 }
    time_stop_minutes: 20160
    use_high_for_targets: true
    exit_on_first_tp: false
    allow_partial_fills: true
